config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :kittens
  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|

      format.html # show.html.erb
      format.json { render json: @kitten }

    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
    redirect_to kitten_path(@kitten), notice: "Kitten has been saved"
    else
    render new_kitten_url
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    kitten = Kitten.find(params[:id])
    kitten.update!(kitten_params)
    redirect_to kitten_path(kitten)
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.delete
    flash.notice="'#{@kitten.name}' record was deleted"

    redirect_to root_url
  end

  private
  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for @kitten do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.number_field :age %>

  <%= f.label :cuteness %>
  <%= f.text_field :cuteness %>

  <%= f.label :softness %>
  <%= f.text_field :softness %>

  <%= f.submit %>
<% end %>

app/views/kittens/edit.html.erb
<%= render "form" %>

app/views/kittens/index.html.erb
<div> All of the kittens below </div><br>

<% @kittens.each do |kitten| %>
<div>Kittens name:<%= link_to kitten.name, kitten_path(kitten) %> <%= button_to "Delete", kitten_path(kitten), :confirm => "Are you sure?", :method => :delete %> </div>
<div>Kittens age:<%=  kitten.age %></div>
<div>Kittens cuteness:<%=  kitten.cuteness %></div>
<div>Kittens name:<%=  kitten.softness %></div><br>
<% end %>

<%= link_to "Add new kitten", "/kittens/new" %>

app/views/kittens/new.html.erb
<%= render "form" %>

app/views/kittens/show.html.erb
<div> Cat Details Below:
Kittens name:<%=  @kitten.name %><br>
Kittens age:<%=  @kitten.age %><br>
Kittens cuteness:<%=  @kitten.cuteness %><br>
Kittens name:<%=  @kitten.softness %> </div>

<%= link_to "Back to home", root_url  %><br>
<%= link_to "Edit Details", edit_kitten_path(@kitten)  %>
<%= button_to "Delete", kitten_path(@kitten), :confirm => "Are you sure?", :method => :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>